# Generated by Django 5.1.15 on 2026-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Поміч поруч', max_length=128, verbose_name='Назва сайту')),
                ('support_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон підтримки')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Email підтримки')),
                ('support_address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('work_hours', models.CharField(blank=True, max_length=128, verbose_name='Години роботи')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('hero_trust_count', models.CharField(default='500+', max_length=32, verbose_name='Hero: кількість нянь')),
                ('hero_trust_cities', models.CharField(default='У 5 містах України', max_length=64, verbose_name='Hero: міста')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
