# Generated by Django 5.1.15 on 2026-06-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('content', models.JSONField(blank=True, default=list, verbose_name='Контент')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='Категорія')),
                ('image_url', models.URLField(blank=True, verbose_name='Зображення')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Стаття блогу',
                'verbose_name_plural': 'Статті блогу',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('how-it-works', 'Як це працює'), ('services', 'Послуги'), ('public-offer', 'Публічна оферта'), ('terms-of-service', 'Terms of Service'), ('privacy-policy', 'Privacy Policy'), ('cookie-policy', 'Cookie Policy'), ('contacts', 'Контакти')], max_length=64, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML контент')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статична сторінка',
                'verbose_name_plural': 'Статичні сторінки',
            },
        ),
    ]
