"""Підказки для полів CMS — що саме редагує користувач на сайті."""

BLOCK_FIELD_HELP: dict[tuple[str, str], str] = {
  # Hero
  ("home", "hero_title_html"): "Обгорніть важливі слова зірочками: Надійна *няня поруч* — для вашої родини. HTML писати не потрібно.",
  ("home", "hero_subtitle"): "Короткий опис під заголовком — 1–2 речення про сервіс.",
  ("home", "search_city_label"): "Підпис над полем вибору міста у формі пошуку.",
  ("home", "search_date_label"): "Підпис над полем дати у формі пошуку.",
  ("home", "search_format_label"): "Підпис над полем формату роботи (погодинно, на день тощо).",
  ("home", "search_submit"): "Текст на кнопці «Знайти няню» у формі пошуку.",
  ("home", "hero_image"): "Фото у Hero-блоці головної сторінки. Рекомендований розмір — 600×750px (портрет), формат JPG/PNG/WebP.",
  ("home", "hero_image_alt"): "Короткий опис фото для людей з обмеженим зором і пошукових систем.",
  ("home", "hero_trust_icon"): "Один емодзі або символ біля бейджа довіри (наприклад, 🛡).",
  ("home", "hero_trust_count"): "Текст про кількість перевірених нянь — під заголовком.",
  ("home", "hero_trust_cities"): "Текст про географію сервісу — під кількістю нянь.",
  # Benefits
  ("home", "benefit_1_icon"): "Емодзі або символ для картки переваги.",
  ("home", "benefit_1_title"): "Короткий заголовок картки.",
  ("home", "benefit_1_text"): "1–2 речення опису переваги.",
  ("home", "benefit_2_icon"): "Емодзі або символ для картки переваги.",
  ("home", "benefit_2_title"): "Короткий заголовок картки.",
  ("home", "benefit_2_text"): "1–2 речення опису переваги.",
  ("home", "benefit_3_icon"): "Емодзі або символ для картки переваги.",
  ("home", "benefit_3_title"): "Короткий заголовок картки.",
  ("home", "benefit_3_text"): "1–2 речення опису переваги.",
  ("home", "benefit_4_icon"): "Емодзі або символ для картки переваги.",
  ("home", "benefit_4_title"): "Короткий заголовок картки.",
  ("home", "benefit_4_text"): "1–2 речення опису переваги.",
  # Steps
  ("home", "steps_title"): "Заголовок секції «Як це працює».",
  ("home", "steps_subtitle"): "Підзаголовок під основним заголовком секції.",
  ("home", "step_1_title"): "Назва першого кроку.",
  ("home", "step_1_desc"): "Короткий опис першого кроку.",
  ("home", "step_2_title"): "Назва другого кроку.",
  ("home", "step_2_desc"): "Короткий опис другого кроку.",
  ("home", "step_3_title"): "Назва третього кроку.",
  ("home", "step_3_desc"): "Короткий опис третього кроку.",
  ("home", "step_4_title"): "Назва четвертого кроку.",
  ("home", "step_4_desc"): "Короткий опис четвертого кроку.",
  # Sections
  ("home", "featured_section_visible"): "Увімкніть, щоб показувати блок «Популярні няні» на головній.",
  ("home", "featured_title"): "Заголовок блоку з картками нянь.",
  ("home", "featured_cta"): "Текст кнопки переходу до повного каталогу.",
  ("home", "cities_section_visible"): "Увімкніть, щоб показувати блок вибору міст.",
  ("home", "cities_title"): "Заголовок блоку з містами.",
  ("home", "city_kyiv_label"): "Назва кнопки міста Київ.",
  ("home", "city_lviv_label"): "Назва кнопки міста Львів.",
  ("home", "city_dnipro_label"): "Назва кнопки міста Дніпро.",
  ("home", "sticky_cta_label"): "Текст кнопки, що зʼявляється внизу екрана на мобільних.",
  # Header
  ("site", "header_brand_uk"): "Назва сайту поруч із логотипом у шапці.",
  ("site", "header_nav_home"): "Пункт меню «Головна».",
  ("site", "header_nav_how"): "Пункт меню «Як це працює».",
  ("site", "header_nav_catalog"): "Пункт меню «Каталог нянь».",
  ("site", "header_nav_blog"): "Пункт меню «Блог».",
  ("site", "header_nav_faq"): "Пункт меню «FAQ».",
  ("site", "header_nav_contacts"): "Пункт меню «Контакти».",
  ("site", "header_btn_search"): "Текст кнопки пошуку у шапці.",
  ("site", "header_btn_register"): "Текст кнопки реєстрації.",
  ("site", "header_btn_login"): "Текст кнопки входу.",
  ("site", "header_mobile_menu"): "Заголовок, що зʼявляється над мобільним меню.",
  # Footer
  ("site", "footer_brand_uk"): "Назва бренду у підвалі сайту.",
  ("site", "footer_desc"): "Короткий опис сервісу під назвою бренду.",
  ("site", "footer_col_nav"): "Заголовок колонки з посиланнями навігації.",
  ("site", "footer_col_legal"): "Заголовок колонки з юридичними посиланнями.",
  ("site", "footer_col_contacts"): "Заголовок колонки з контактами.",
  ("site", "footer_link_contact"): "Текст посилання «Звʼязатись».",
  ("site", "footer_link_services"): "Текст посилання «Послуги».",
  ("site", "footer_email"): "Email, що відображається у підвалі.",
  ("site", "footer_phone"): "Телефон, що відображається у підвалі.",
  ("site", "footer_copyright"): "Рядок copyright внизу сторінки.",
  ("site", "footer_tech"): "Технічний рядок під copyright (необовʼязково).",
  # Cookie
  ("site", "cookie_title"): "Заголовок спливаючого банера cookies.",
  ("site", "cookie_body"): "Основний текст банера без посилання.",
  ("site", "cookie_body_link"): "Текст посилання «Детальніше» — можна додати посилання через редактор.",
  ("site", "cookie_accept"): "Кнопка прийняття всіх cookies.",
  ("site", "cookie_reject"): "Кнопка відмови від необовʼязкових cookies.",
  ("site", "cookie_settings"): "Кнопка відкриття налаштувань cookies.",
  ("site", "cookie_save"): "Кнопка збереження налаштувань cookies.",
  ("site", "cookie_toggle_necessary"): "Підпис перемикача «Необхідні» cookies.",
  ("site", "cookie_toggle_analytics"): "Підпис перемикача аналітичних cookies.",
  ("site", "cookie_toggle_marketing"): "Підпис перемикача маркетингових cookies.",
  # Catalog
  ("catalog", "catalog_title"): "Великий заголовок сторінки каталогу нянь.",
  ("catalog", "catalog_subtitle"): "Підзаголовок під заголовком каталогу.",
  ("catalog", "catalog_filters_title"): "Заголовок панелі фільтрів зліва.",
  ("catalog", "catalog_filters_toggle"): "Текст кнопки відкриття фільтрів на мобільних.",
  # Auth
  ("auth", "auth_trust_1"): "Перший бейдж довіри на сторінці входу/реєстрації.",
  ("auth", "auth_trust_2"): "Другий бейдж довіри.",
  ("auth", "auth_trust_3"): "Третій бейдж довіри.",
  ("auth", "auth_login_title"): "Заголовок форми входу.",
  ("auth", "auth_login_divider"): "Текст між соцмережами та полем email.",
  ("auth", "auth_login_submit"): "Текст кнопки «Увійти».",
  ("auth", "auth_login_footer"): "Текст під формою входу — можна додати посилання через редактор.",
  ("auth", "auth_register_title"): "Заголовок форми реєстрації.",
  ("auth", "auth_register_submit"): "Текст кнопки «Зареєструватись».",
  ("auth", "auth_register_footer"): "Текст під формою реєстрації — можна додати посилання через редактор.",
}


def field_help_for(page: str, key: str) -> str:
    return BLOCK_FIELD_HELP.get((page, key), "")
