"""CMS block defaults — без імпорту models."""

VISIBILITY_SUFFIX = "_visible"
INLINE_KEYS = frozenset(
    {
        "hero_trust_icon",
        "hero_trust_count",
        "hero_trust_cities",
        "search_city_label",
        "search_date_label",
        "search_format_label",
        "search_submit",
        "benefit_1_icon",
        "benefit_2_icon",
        "benefit_3_icon",
        "benefit_4_icon",
        "step_1_title",
        "step_2_title",
        "step_3_title",
        "step_4_title",
        "featured_cta",
        "sticky_cta_label",
        "city_kyiv_label",
        "city_lviv_label",
        "city_dnipro_label",
        "header_brand_uk",
        "header_nav_home",
        "header_nav_how",
        "header_nav_catalog",
        "header_nav_blog",
        "header_nav_faq",
        "header_nav_contacts",
        "header_btn_search",
        "header_btn_register",
        "header_btn_login",
        "header_mobile_menu",
        "footer_brand_uk",
        "footer_col_nav",
        "footer_col_legal",
        "footer_col_contacts",
        "footer_link_contact",
        "footer_link_services",
        "footer_email",
        "footer_phone",
        "footer_copyright",
        "footer_tech",
        "cookie_title",
        "cookie_accept",
        "cookie_reject",
        "cookie_settings",
        "cookie_save",
        "cookie_toggle_necessary",
        "cookie_toggle_analytics",
        "cookie_toggle_marketing",
        "catalog_title",
        "catalog_filters_title",
        "catalog_filters_toggle",
        "auth_trust_1",
        "auth_trust_2",
        "auth_trust_3",
        "auth_login_title",
        "auth_login_divider",
        "auth_login_submit",
        "auth_register_title",
        "auth_register_submit",
        "hero_title_html",
        "cookie_body_link",
    }
)
ACCENT_MARKER_KEYS = frozenset({"hero_title_html"})
IMAGE_KEYS = frozenset({"hero_image"})
MULTILINE_KEYS = frozenset(
    {
        "hero_subtitle",
        "footer_desc",
        "cookie_body",
        "catalog_subtitle",
        "auth_login_footer",
        "auth_register_footer",
        "benefit_1_text",
        "benefit_2_text",
        "benefit_3_text",
        "benefit_4_text",
        "step_1_desc",
        "step_2_desc",
        "step_3_desc",
        "step_4_desc",
    }
)


def is_visibility_key(key: str) -> bool:
    return key.endswith(VISIBILITY_SUFFIX)


def is_image_key(key: str) -> bool:
    return key in IMAGE_KEYS


def default_for_key(page: str, key: str) -> str:
    return BLOCK_DEFAULTS.get((page, key), "1" if is_visibility_key(key) else "")


BLOCK_FIELD_LABELS: dict[tuple[str, str], str] = {
    ("home", "hero_section_visible"): "Показувати секцію Hero",
    ("home", "hero_title_html"): "Головний заголовок",
    ("home", "hero_subtitle"): "Текст під заголовком",
    ("home", "search_city_label"): "Поле «Місто»",
    ("home", "search_date_label"): "Поле «Дата»",
    ("home", "search_format_label"): "Поле «Формат»",
    ("home", "search_submit"): "Кнопка пошуку",
    ("home", "hero_image"): "Фото у Hero-блоці",
    ("home", "hero_image_alt"): "Опис фото",
    ("home", "hero_trust_icon"): "Іконка бейджа",
    ("home", "hero_trust_count"): "Кількість нянь",
    ("home", "hero_trust_cities"): "Міста",
    ("home", "benefits_section_visible"): "Показувати секцію «Переваги»",
    ("home", "benefit_1_icon"): "Іконка",
    ("home", "benefit_1_title"): "Заголовок",
    ("home", "benefit_1_text"): "Опис",
    ("home", "benefit_2_icon"): "Іконка",
    ("home", "benefit_2_title"): "Заголовок",
    ("home", "benefit_2_text"): "Опис",
    ("home", "benefit_3_icon"): "Іконка",
    ("home", "benefit_3_title"): "Заголовок",
    ("home", "benefit_3_text"): "Опис",
    ("home", "benefit_4_icon"): "Іконка",
    ("home", "benefit_4_title"): "Заголовок",
    ("home", "benefit_4_text"): "Опис",
    ("home", "steps_section_visible"): "Показувати секцію «Як працює»",
    ("home", "steps_title"): "Заголовок секції кроків",
    ("home", "steps_subtitle"): "Підзаголовок секції кроків",
    ("home", "step_1_title"): "Заголовок кроку",
    ("home", "step_1_desc"): "Опис кроку",
    ("home", "step_2_title"): "Заголовок кроку",
    ("home", "step_2_desc"): "Опис кроку",
    ("home", "step_3_title"): "Заголовок кроку",
    ("home", "step_3_desc"): "Опис кроку",
    ("home", "step_4_title"): "Заголовок кроку",
    ("home", "step_4_desc"): "Опис кроку",
    ("home", "featured_section_visible"): "Показувати «Популярні няні»",
    ("home", "featured_title"): "Заголовок «Популярні няні»",
    ("home", "featured_cta"): "Кнопка «Усі профілі»",
    ("home", "cities_section_visible"): "Показувати «Няні у місті»",
    ("home", "cities_title"): "Заголовок «Няні у місті»",
    ("home", "city_kyiv_label"): "Кнопка міста: Київ",
    ("home", "city_lviv_label"): "Кнопка міста: Львів",
    ("home", "city_dnipro_label"): "Кнопка міста: Дніпро",
    ("home", "sticky_cta_label"): "Sticky-кнопка внизу екрана",
    ("site", "header_brand_uk"): "Назва бренду (UA)",
    ("site", "header_nav_home"): "Меню: Головна",
    ("site", "header_nav_how"): "Меню: Як це працює",
    ("site", "header_nav_catalog"): "Меню: Каталог нянь",
    ("site", "header_nav_blog"): "Меню: Блог",
    ("site", "header_nav_faq"): "Меню: FAQ",
    ("site", "header_nav_contacts"): "Меню: Контакти",
    ("site", "header_btn_search"): "Кнопка «Знайти няню»",
    ("site", "header_btn_register"): "Кнопка «Реєстрація»",
    ("site", "header_btn_login"): "Кнопка «Увійти»",
    ("site", "header_mobile_menu"): "Заголовок мобільного меню",
    ("site", "footer_brand_uk"): "Назва бренду в підвалі",
    ("site", "footer_desc"): "Опис під брендом",
    ("site", "footer_col_nav"): "Колонка: Навігація",
    ("site", "footer_col_legal"): "Колонка: Юридичне",
    ("site", "footer_col_contacts"): "Колонка: Контакти",
    ("site", "footer_link_contact"): "Посилання «Зв'язатись»",
    ("site", "footer_link_services"): "Посилання «Послуги»",
    ("site", "footer_email"): "Email у підвалі",
    ("site", "footer_phone"): "Телефон у підвалі",
    ("site", "footer_copyright"): "Copyright",
    ("site", "footer_tech"): "Технічний рядок",
    ("site", "cookie_title"): "Заголовок банера",
    ("site", "cookie_body"): "Текст банера",
    ("site", "cookie_body_link"): "Посилання «Детальніше»",
    ("site", "cookie_accept"): "Кнопка «Прийняти всі»",
    ("site", "cookie_reject"): "Кнопка «Лише необхідні»",
    ("site", "cookie_settings"): "Кнопка «Налаштування»",
    ("site", "cookie_save"): "Кнопка «Зберегти»",
    ("site", "cookie_toggle_necessary"): "Перемикач «Необхідні»",
    ("site", "cookie_toggle_analytics"): "Перемикач «Аналітика»",
    ("site", "cookie_toggle_marketing"): "Перемикач «Маркетинг»",
    ("catalog", "catalog_title"): "Заголовок сторінки каталогу",
    ("catalog", "catalog_subtitle"): "Підзаголовок каталогу",
    ("catalog", "catalog_filters_title"): "Заголовок панелі фільтрів",
    ("catalog", "catalog_filters_toggle"): "Кнопка «Показати фільтри»",
    ("auth", "auth_trust_1"): "Бейдж довіри 1",
    ("auth", "auth_trust_2"): "Бейдж довіри 2",
    ("auth", "auth_trust_3"): "Бейдж довіри 3",
    ("auth", "auth_login_title"): "Заголовок форми",
    ("auth", "auth_login_divider"): "Текст «або email»",
    ("auth", "auth_login_submit"): "Кнопка входу",
    ("auth", "auth_login_footer"): "Текст під формою входу",
    ("auth", "auth_register_title"): "Заголовок форми",
    ("auth", "auth_register_submit"): "Кнопка реєстрації",
    ("auth", "auth_register_footer"): "Текст під формою реєстрації",
}

BLOCK_DEFAULTS: dict[tuple[str, str], str] = {
    ("home", "hero_section_visible"): "1",
    ("home", "hero_title_html"): "Надійна *няня поруч* — для вашої родини",
    ("home", "hero_subtitle"): "Знайдіть перевіреного помічника за лічені хвилини. Безпечний пошук, прозорі профілі та зручний чат.",
    ("home", "search_city_label"): "🏙 Місто",
    ("home", "search_date_label"): "📅 Дата",
    ("home", "search_format_label"): "Формат",
    ("home", "search_submit"): "🔍 Знайти няню",
    ("home", "hero_image_alt"): "Няня з дитиною",
    ("home", "hero_trust_icon"): "🛡",
    ("home", "hero_trust_count"): "500+ перевірених нянь",
    ("home", "hero_trust_cities"): "У 5 містах України",
    ("home", "benefits_section_visible"): "1",
    ("home", "benefit_1_icon"): "🛡",
    ("home", "benefit_1_title"): "Перевірені профілі",
    ("home", "benefit_1_text"): "Модерація документів кожної няні",
    ("home", "benefit_2_icon"): "🔒",
    ("home", "benefit_2_title"): "Безпечний пошук",
    ("home", "benefit_2_text"): "GDPR та ЗУ про захист даних",
    ("home", "benefit_3_icon"): "👥",
    ("home", "benefit_3_title"): "Велика база",
    ("home", "benefit_3_text"): "Сотні профілів у містах України",
    ("home", "benefit_4_icon"): "⚡",
    ("home", "benefit_4_title"): "Швидкий підбір",
    ("home", "benefit_4_text"): "Знайдіть няню за лічені хвилини",
    ("home", "steps_section_visible"): "1",
    ("home", "steps_title"): "Як це працює",
    ("home", "steps_subtitle"): "Чотири простих кроки",
    ("home", "step_1_title"): "Переглядайте або зареєструйтесь",
    ("home", "step_1_desc"): "Гості можуть шукати без акаунта. Батьки та помічники — окремі кабінети",
    ("home", "step_2_title"): "Оберіть няню",
    ("home", "step_2_desc"): "Використовуйте фільтри та переглядайте профілі",
    ("home", "step_3_title"): "Відкрийте контакти",
    ("home", "step_3_desc"): "Батьки оформлюють підписку для доступу до телефонів",
    ("home", "step_4_title"): "Домовтесь",
    ("home", "step_4_desc"): "Спишіться в чаті про співбесіду онлайн або зустріч",
    ("home", "featured_section_visible"): "1",
    ("home", "featured_title"): "Популярні няні",
    ("home", "featured_cta"): "Усі профілі",
    ("home", "cities_section_visible"): "1",
    ("home", "cities_title"): "Няні у вашому місті",
    ("home", "city_kyiv_label"): "Київ",
    ("home", "city_lviv_label"): "Львів",
    ("home", "city_dnipro_label"): "Дніпро",
    ("home", "sticky_cta_label"): "Знайти няню",
    ("site", "header_brand_uk"): "Поміч поруч",
    ("site", "header_nav_home"): "Головна",
    ("site", "header_nav_how"): "Як це працює",
    ("site", "header_nav_catalog"): "Каталог нянь",
    ("site", "header_nav_blog"): "Блог",
    ("site", "header_nav_faq"): "FAQ",
    ("site", "header_nav_contacts"): "Контакти",
    ("site", "header_btn_search"): "🔍 Знайти няню",
    ("site", "header_btn_register"): "Реєстрація",
    ("site", "header_btn_login"): "Увійти",
    ("site", "header_mobile_menu"): "Меню",
    ("site", "footer_brand_uk"): "Поміч поруч",
    ("site", "footer_desc"): "Маркетплейс пошуку нянь та помічників. Безпечно, швидко, надійно.",
    ("site", "footer_col_nav"): "Навігація",
    ("site", "footer_col_legal"): "Юридичне",
    ("site", "footer_col_contacts"): "Контакти",
    ("site", "footer_link_contact"): "Зв'язатись з нами",
    ("site", "footer_link_services"): "Послуги",
    ("site", "footer_email"): "info@pomich-poruch.com.ua",
    ("site", "footer_phone"): "+380 44 123 45 67",
    ("site", "footer_copyright"): "© 2026 Поміч поруч. Всі права захищені.",
    ("site", "footer_tech"): "HTML · HTMX · JavaScript",
    ("site", "cookie_title"): "🍪 Ми використовуємо cookies",
    ("site", "cookie_body"): "Відповідно до ЗУ «Про захист персональних даних» та GDPR.",
    ("site", "cookie_body_link"): "Детальніше",
    ("site", "cookie_accept"): "Прийняти всі",
    ("site", "cookie_reject"): "Лише необхідні",
    ("site", "cookie_settings"): "Налаштування",
    ("site", "cookie_save"): "Зберегти",
    ("site", "cookie_toggle_necessary"): "Необхідні",
    ("site", "cookie_toggle_analytics"): "Аналітика",
    ("site", "cookie_toggle_marketing"): "Маркетинг",
    ("catalog", "catalog_title"): "Каталог нянь",
    ("catalog", "catalog_subtitle"): "10 фільтрів: місто, район, вік, досвід, ставка, рейтинг та інше",
    ("catalog", "catalog_filters_title"): "Фільтри",
    ("catalog", "catalog_filters_toggle"): "Показати фільтри",
    ("auth", "auth_trust_1"): "Перевірені профілі",
    ("auth", "auth_trust_2"): "Захист даних",
    ("auth", "auth_trust_3"): "Чат у кабінеті",
    ("auth", "auth_login_title"): "Вхід",
    ("auth", "auth_login_divider"): "або email",
    ("auth", "auth_login_submit"): "Увійти",
    ("auth", "auth_login_footer"): 'Немає акаунту? <a href="/register">Зареєструватись</a> · <a href="/forgot-password">Забули пароль?</a>',
    ("auth", "auth_register_title"): "Реєстрація",
    ("auth", "auth_register_submit"): "Створити акаунт",
    ("auth", "auth_register_footer"): '<a href="/login">Вже маю акаунт</a>',
}


def all_registry_block_keys() -> tuple[tuple[str, str], ...]:
    return tuple(BLOCK_DEFAULTS.keys())
