# Generated by Django 5.1.15 on 2026-06-25 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NannyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Прізвище')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('photo', models.ImageField(blank=True, upload_to='nannies/photos/', verbose_name='Фото')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL фото')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('hourly_rate', models.PositiveIntegerField(default=300, verbose_name='Ставка ₴/год')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Роки досвіду')),
                ('families_count', models.PositiveSmallIntegerField(default=0, verbose_name="Сім'ї")),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендації')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='Мови')),
                ('certificates', models.JSONField(blank=True, default=list, verbose_name='Сертифікати')),
                ('has_car', models.BooleanField(default=False, verbose_name='Має авто')),
                ('medical_education', models.BooleanField(default=False, verbose_name='Медична освіта')),
                ('first_aid_course', models.BooleanField(default=False, verbose_name='Курс першої допомоги')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Перевірено')),
                ('moderation_status', models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=16, verbose_name='Модерація')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Відгуки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nannies', to='geo.city', verbose_name='Місто')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nannies', to='geo.district', verbose_name='Район')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nanny_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль няні',
                'verbose_name_plural': 'Профілі нянь',
                'ordering': ['-rating_avg', '-review_count'],
            },
        ),
        migrations.CreateModel(
            name='NannyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('passport', 'Паспорт'), ('ipn', 'ІПН'), ('criminal_record', 'Довідка про несудимість')], max_length=32, verbose_name='Тип')),
                ('file', models.FileField(upload_to='nannies/documents/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('approved', 'OK'), ('rejected', 'Відхилено')], default='pending', max_length=16, verbose_name='Статус')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='nannies.nannyprofile')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('busy', 'Зайнята'), ('vacation', 'Відпустка')], default='available', max_length=16, verbose_name='Статус')),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nannies.nannyprofile')),
            ],
            options={
                'verbose_name': 'Доступність',
                'verbose_name_plural': 'Доступність',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='nannyprofile',
            index=models.Index(fields=['city', 'is_verified'], name='nannies_nan_city_id_d79ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='nannyprofile',
            index=models.Index(fields=['moderation_status'], name='nannies_nan_moderat_6856db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='nannydocument',
            unique_together={('nanny', 'doc_type')},
        ),
        migrations.AlterUniqueTogether(
            name='availabilityslot',
            unique_together={('nanny', 'date')},
        ),
    ]
