# Generated by Django 5.1.15 on 2026-06-25 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('nannies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Прізвище')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість дітей')),
                ('children_ages', models.CharField(blank=True, max_length=128, verbose_name='Вік дітей')),
                ('special_needs', models.TextField(blank=True, verbose_name='Особливі потреби')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='geo.city', verbose_name='Місто')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль батьків',
                'verbose_name_plural': 'Профілі батьків',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='nannies.nannyprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Обране',
                'verbose_name_plural': 'Обране',
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'nanny')},
            },
        ),
        migrations.CreateModel(
            name='ContactUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks', to='nannies.nannyprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks', to='parents.parentprofile')),
            ],
            options={
                'verbose_name': 'Відкритий контакт',
                'verbose_name_plural': 'Відкриті контакти',
                'unique_together': {('parent', 'nanny')},
            },
        ),
    ]
