# Generated by Django 5.1.15 on 2026-06-25 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=128, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price_uah', models.PositiveIntegerField(verbose_name='Ціна ₴')),
                ('plan_type', models.CharField(choices=[('single', '1 контакт'), ('pack5', '5 контактів'), ('city7', 'Місто · 7 днів')], max_length=16, verbose_name='Тип')),
                ('contact_limit', models.PositiveSmallIntegerField(default=1, verbose_name='Контактів')),
                ('city_access_days', models.PositiveSmallIntegerField(default=0, verbose_name='Днів доступу')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
                'ordering': ['price_uah'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay'), ('wayforpay', 'WayForPay'), ('fondy', 'Fondy'), ('stub', 'Stub')], max_length=16, verbose_name='Провайдер')),
                ('amount_uah', models.PositiveIntegerField(verbose_name='Сума ₴')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('paid', 'Оплачено'), ('failed', 'Помилка'), ('refunded', 'Повернено')], default='pending', max_length=16, verbose_name='Статус')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='ID провайдера')),
                ('order_reference', models.CharField(max_length=64, unique=True, verbose_name='Order ref')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.pricingplan')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_remaining', models.PositiveSmallIntegerField(default=0, verbose_name='Контактів залишилось')),
                ('city_access_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Завершена'), ('cancelled', 'Скасована')], default='active', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='parents.parentprofile')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='payments.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.pricingplan')),
            ],
            options={
                'verbose_name': 'Підписка',
                'verbose_name_plural': 'Підписки',
                'ordering': ['-started_at'],
            },
        ),
    ]
